name: Tag on Push to Master

on:
  push:
    branches:
      - master

jobs:
  tag_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate a GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Git tag
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}-${{ github.sha }}"
          git tag $TAG_NAME
          echo "Created tag $TAG_NAME"

      - name: Push the tag using GitHub App token
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          TAG_NAME="v1.0.${{ github.run_number }}-${{ github.sha }}"
          git push https://x-access-token:${{ env.GH_TOKEN }}@github.com/${{ github.repository }} $TAG_NAME
