name: Tag on Push to Master

on:
  push:
    branches:
      - master

jobs:
  tag_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get the current commit hash
        id: get_commit
        run: echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Create Git tag using GitHub API
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.generate-token.outputs.token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/git/tags \
            -d '{
              "tag": "v1.0.${{ github.run_number }}-${{ steps.get_commit.outputs.sha }}",
              "message": "Tagging commit for v1.0.${{ github.run_number }}",
              "object": "${{ env.COMMIT_SHA }}",
              "type": "commit",
              "tagger": {
                "name": "GitHub Actions",
                "email": "actions@github.com",
                "date": "'$(date --utc +%Y-%m-%dT%H:%M:%SZ)'"
              }
            }'

      - name: Push the tag
        run: |
          git push origin refs/tags/v1.0.${{ github.run_number }}-${{ steps.get_commit.outputs.sha }}
