name: Tag on Push to Master

on:
  push:
    branches:
      - master

jobs:
  tag_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Git tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag v1.0.${{ github.run_number }}-${{ github.sha }}
          git push --tags https://${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository }}

      - name: Tagging done
        run: echo "Tagged with v1.0.${{ github.run_number }}-${{ github.sha }}"
